# Generated by Django 5.1.7 on 2025-06-09 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, choices=[('Librarian', 'Librarian'), ('Member', 'Member')], default=None, max_length=20, null=True),
        ),
    ]
