# Generated by Django 5.1.7 on 2025-06-09 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0003_borrow_borrowitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowitem',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Borrowed', max_length=10),
        ),
    ]
