# Generated by Django 5.1.7 on 2025-06-09 12:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0004_borrowitem_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowitem',
            name='borrow_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 6, 1, 0, 0, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
