# Generated by Django 5.1.7 on 2025-06-09 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('borrow', '0005_borrowitem_borrow_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrowitem',
            name='status',
        ),
        migrations.AddField(
            model_name='borrow',
            name='status',
            field=models.CharField(choices=[('Borrowed', 'Borrowed'), ('Returned', 'Returned'), ('Overdue', 'Overdue')], default='Borrowed', max_length=10),
        ),
    ]
